variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY_IMAGE: vanthang24803/amak-client
  IMAGE_TAG: 1.0.0

stages:
  - build
  - push

before_script:
  - docker info

build_image:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
  only:
    - main
  tags:
    - docker

push_image:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  only:
    - main
  tags:
    - docker
