version: "3.8"
services:
  fe:
    container_name: amak_fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - amak

  nginx:
    image: nginx:alpine
    container_name: amak_fe_nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - amak_fe
    networks: amak

networks:
  amak:
    driver: bridge
