version: "3.8"
services:
  fe:
    container_name: amak_fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - amak

  api:
    container_name: amak_be
    image: vanthang24803/amak-api-prod:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://*:8080
    depends_on:
      - redis
    networks:
      - amak

  redis:
    image: redis:latest
    container_name: amak_prod_redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - amak

networks:
  amak:
    driver: bridge

volumes:
  redis-data:
