version: "3.8"
services:
  fe:
    container_name: amak_fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - amak

  be:
    container_name: amak_be
    image: vanthang24803/amak-api-prod:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://*:8080
    depends_on:
      - redis
      - rabbitmq
    networks:
      - amak

  redis:
    image: redis:latest
    container_name: amak_prod_redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - amak

  rabbitmq:
    image: rabbitmq:latest
    container_name: amak_prod_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - amak
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  nginx:
    image: nginx:alpine
    container_name: amak_fe_nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - amak_fe
    networks: amak

networks:
  amak:
    driver: bridge

volumes:
  redis-data:
